package org.example.types;

public enum RequestType {
    AUTH,
    ALL_USER, ALL_USER_INFO_EMPLOYEE, ALL_POSTS, ADD_EMPLOYEE, ADD_USER, DELETE_USER, EDIT_USER, DELETE_EMPLOYEE, ADD_POST, EDIT_POST, DELETE_POST, ALL_NEWS, ADD_NEWS, EDIT_NEWS, DELETE_NEWS, MY_ALL_ORDER, GET_MY_CONTACT, CREATE_ORDER, DELETE_ORDER, ALL_ORDER_CHART, ALL_ORDER, EDIT_STATUS, CHANGE_ORDER_STATUS, ALL_PROJECT, PROJECT_STATUS, ALL_ALLOWANCE, DELETE_ALLOWANCE, EDIT_ALLOWANCE, CALCULATE_ONE, CALCULATE_THREE, CALCULATE_TWO, ALL_APTITUDE, EDIT_APTITUDE, DELETE_APTITUDE, ADD_APTITUDE, REG
}
